### ISSUE TITLE
Order of the Buttons

### ISSUE THREAD

**Issue by veganstraightedge** [kypsy/website#11]
> The current layout feels like counterintuitive to me (see below). Can we reverse the order of the buttons as well as the direction of the arrow in the “Next” button? (i.e. change from “<- Next / Bookmark / YASS” to “YASS / Bookmark / Next ->”). I understand this was the order that was initially requested, but it does seem weird when I actually see it on the website. If the changing the order of the buttons is too much work for you at this point, can you at least change the direction of the arrow in the “<- Next” button to “Next ->”?

![p94](https://cloud.githubusercontent.com/assets/4361/26758084/d5db45ae-4888-11e7-968a-fd306747100b.png)

**Comment by mj90291** [comment]
Fix verified. Thank you.
