### ISSUE TITLE
My profile picture is not visible when visiting my own page as seen below

### ISSUE THREAD

**Issue by veganstraightedge** [kypsy/website#2]
![p94](https://cloud.githubusercontent.com/assets/4361/26757930/6ba21ace-4882-11e7-9db7-9e7a61ade884.png)

> As you can see, my profile picture has been clearly uploaded, but only visible under the “People Using Kypsy” page  (i.e. the page where you can see when you click on the 3 people symbol at the top right to browse through other members)

![p94](https://cloud.githubusercontent.com/assets/4361/26757932/7c256108-4882-11e7-976b-dafdf90d3777.png)

> I uploaded to additional photos for testing, and the photo display results varied between my own profile page vs. the “People Using Kypsy” page 
>
> On my own profile page, I still do not see my main profile picture which on the other hand is visible in the People Using Kypsy” page. See below.

![p94](https://cloud.githubusercontent.com/assets/4361/26757935/947196b4-4882-11e7-84cc-a1e5135aa38e.png)

**Comment by veganstraightedge** [comment]
Like in #5, this is the case of two accounts.

Take note in your screenshots that the first screenshot is of @maxine. The second one is of @maxi.

If I delete @maxine, the confusion will be gone.

**Comment by mj90291** [comment]
Please see my answer at #5.
