### ISSUE TITLE
Wrong profile photo

### ISSUE THREAD

**Issue by veganstraightedge** [kypsy/website#3]
> I asked my friend John to sign in and send me screen captures of my profile. Below are what he sent me. As you can see, you still cannot see my main pic in any of them: 
> When viewing my profile through "People Using Kypsy” page:

![p94](https://cloud.githubusercontent.com/assets/4361/26758040/4b66730e-4887-11e7-948c-56bce47f50b6.png)

**Comment by veganstraightedge** [comment]
This is also the case of you having two accounts, as laid out in #5.

If I delete the @maxine account, that'll fix this.

**Comment by mj90291** [comment]
Please see my answer at #5.
