### ISSUE TITLE
Users shouldn't see themselves on /people

### ISSUE THREAD

**Issue by veganstraightedge** [kypsy/website#5]
> On a related note, my own profile page should not be visible under that page where you browse through other members (i.e. “People Using Kypsy”). You agreed with me in your email a couple weeks ago and as you can see above, the problem is there. Can you please fix it?

**Comment by veganstraightedge** [comment]
Users can't see themselves on /people. What has happened is that you've created two accounts.

https://kypsy.com/@maxi
https://kypsy.com/@maxine

So, what you're seeing on /people when you're signed in as @maxi is @maxine. And vice versa.

This can be resolved by you or I deleting your original account: @maxine.

Are you ok with me doing that?

**Comment by mj90291** [comment]
Ahahaha! This is killing me! Thanks for the clarification and sorry about the confusion. 

1. Can we actually keep @maxine, and delete @maxi?

2. BTW, how was I able to create 2 accounts if I used the same FB or Twitter info? 
Did one of them get created with Twitter and the other with FB?

**Comment by mj90291** [comment]
Please see my answer at https://github.com/kypsy/website/issues/5

**Comment by veganstraightedge** [comment]
1. Yep. Done.

2. You created @maxi with FB and @maxine with Twitter.
